# Configuration file for pre-commit hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks  # Main Pre-commit hook
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
        exclude: '\.ipynb$'

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--line-length=100]

# Python Sorter hook
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --filter-files]

      # Python Linter hook
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [--count, --show-source, --statistics, '--ignore', 'E203,E501,W503']
        log_file: flake.log
